name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: ${{ github.event_name != 'pull_request' }}
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build and Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "/"  # This is the root folder of your static files
          output_location: "/"  # No build step required, so keep it as root
          api_location: ""  # No Azure Functions are deployed from this static app
